name: Linux (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            7.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/EasyMicroservices.AuthenticationsMicroservice.sln
      - name: Build
        run: dotnet build ./src/CSharp/EasyMicroservices.AuthenticationsMicroservice.sln --no-restore
      - name: Test
        run:  |
          dotnet test ./src/CSharp/EasyMicroservices.AuthenticationsMicroservice.sln --no-build --verbosity normal -f net7.0
